export const types = {
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_FAIL: "AUTH_FAIL",
  AUTH_SUCCESS: "AUTH_SUCESS",
  AUTH_START: "AUTH_START",

  GET_USERDATA: "GET_USERDATA",
  GET_CHAPTERS: "GET_CHAPTERS",
  GET_CHAPTER: "GET_CHAPTER",
  GET_QUIZDATA: "GET_QUIZDATA"
};
